security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_USER, ROLE_APPLICANT]
        ROLE_ADMIN:       [ROLE_USER, ROLE_APPLICANT]
        ROLE_APPLICANT:   ROLE_APPLICANT

    providers:
        main:
            memory:
                users:
                    foo:
                        password:           foo
                        roles:              ROLE_USER
                    bar:
                        password:           bar
                        roles:              [ROLE_USER, ROLE_ADMIN]

    firewalls:
        main:
            pattern: ^/
            logout:       true
            anonymous:    ~
        secured_area:
                    anonymous: ~
                    oauth:
                        resource_owners:
                            stripe: /stripe
                        login_path:        /connect
                        use_forward:       false
                        failure_path:      /stripe

                        oauth_user_provider:
                            oauth: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/menu$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sale$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, roles: ROLE_APPLICANT }
        - { path: ^/contact, roles: ROLE_APPLICANT }
